export enum ActionTypes {
  AUTH_START = 'AUTH_START',
  AUTH_SUCCESS = 'AUTH_SUCCESS',
  AUTH_FAIL = 'AUTH_FAIL',
  SIGN_OUT = 'SIGN_OUT',
  RESET_ERROR = 'RESET_ERROR',

  GET_EMAIL = 'GET_EMAIL',

  FETCH_START = 'FETCH_START',
  FETCH_SUCCESS = 'FETCH_SUCCESS',
  FETCH_FAIL = 'FETCH_FAIL',
  ADD_TASK = 'ADD_TASK',
  COMPLETE_TASK = 'COMPLETE_TASK',
}
